apiVersion: v1
kind: Service
metadata:
  name: target-service
  namespace: scalelab
spec:
  selector:
    app: target-service
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
